spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_test?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: admin

logging:
  level:
    root: INFO
    com.tca.common.data.mybatis.test.mapper: DEBUG
    com.baomidou.mybatisplus: INFO

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  global-config:
    db-config:
      # 全局逻辑删除的实体字段名(since 3.3.0, 配置后可以忽略不配置步骤2)
      logic-delete-field: delete_flag
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0


