spring:
  redis:
    host: 172.16.19.26
    port: 6379
    password: ai123456
    database: 9
    lettuce:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
    timeout: 3000



